stages:
  - lint
  - test
  - build
  - deploy
  - notify

include:
  - project: infra_dss/gitlab-ci-extends/dss-ci-templates
    ref: main
    file: gitleaks.yaml
  - project: infra_dss/gitlab-ci-extends/dss-ci-templates
    ref: main
    file: checkov.gitlab-ci.yml
  - project: infra_dss/gitlab-ci-extends/dss-ci-templates
    ref: main
    file: notify-telegram.gitlab-ci.yml
  - project: infra_dss/gitlab-ci-extends/dss-ci-templates
    ref: dev
    file: docker-build.gitlab-ci.yml

check_secrets:
  stage: lint
  extends: .check_secrets
  allow_failure: true

check_checkov:
  stage: lint
  extends: .check_checkov
  allow_failure: true

deploy_to_dev:
  variables: 
    SERVER_IP: 5.101.51.23
  before_script: 
    - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - ssh-keyscan "$SERVER" >> ~/.ssh/known_hosts 
  script:
    - mkdir -p /opt/apps
    - scp docker-compose.yaml root@:/opt/apps 
    - docker compose up -d